"""
P6B — Docling HDFC Investigation Script
========================================
READ-ONLY benchmark. Does NOT modify any production parser.

Runs Docling layout analysis on the HDFC PDF and extracts:
  - Layout elements (headers, footers, tables, text blocks)
  - Table structures
  - Page-level statistics
  - Footer/Header classification

Outputs (saved to investigations/DOCLING/HDFC/):
  - raw_output.json   : all Docling elements
  - tables.json       : table-only extraction
  - layout.json       : layout classification (header/footer/table/text)
  - summary.md        : findings narrative

Usage:
    & 'Z:\\CA\\investigations\\DOCLING\\docling_env\\Scripts\\python.exe' run_docling_hdfc.py
"""

import json
import os
import sys
import time
from pathlib import Path

# ── Paths ──────────────────────────────────────────────────────────────────────
PDF_PATH = r"Z:\CA\validation_lab\backend\temp\JOB_20260614_233121_48AC_Acct Statement_3644_14032026_13.08.12 1 (1)_page-0006.pdf"
OUT_DIR  = r"Z:\CA\investigations\DOCLING\HDFC"

os.makedirs(OUT_DIR, exist_ok=True)

def save_json(filename: str, data) -> None:
    path = os.path.join(OUT_DIR, filename)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False, default=str)
    print(f"   Saved: {path}")

# ── Check Docling available ────────────────────────────────────────────────────
try:
    import docling
    from docling.document_converter import DocumentConverter
    from docling.datamodel.base_models import InputFormat
    from docling.datamodel.document import DoclingDocument
    print(f"✓ Docling version: {docling.__version__}")
except ImportError as e:
    print(f"ERROR: Docling not installed in this environment: {e}")
    print("Run: pip install docling>=2.59.0")
    sys.exit(1)

print("=" * 70)
print("P6B — Docling HDFC Investigation")
print("=" * 70)
print(f"PDF: {os.path.basename(PDF_PATH)}")
print(f"Output: {OUT_DIR}")
print()

# ── Step 1: Run Docling ────────────────────────────────────────────────────────
print("STEP 1: Running Docling document conversion...")
t0 = time.time()

converter = DocumentConverter()
result = converter.convert(PDF_PATH)
doc: DoclingDocument = result.document

elapsed = time.time() - t0
print(f"   Completed in {elapsed:.1f}s")

# ── Step 2: Extract all elements ───────────────────────────────────────────────
print("STEP 2: Extracting layout elements...")

raw_elements = []
tables_data  = []
layout_data  = {
    "headers": [],
    "footers": [],
    "tables": [],
    "text_blocks": [],
    "page_stats": {},
}

# Iterate over document items
header_keywords  = {"hdfc bank", "statement of account", "from:", "to:", "branch", "generated on", "generated by", "requesting branch"}
footer_keywords  = {"registered office", "closing balance includes", "gstn", "mumbai", "senapati bapat", "lowe parel", "t branchgstn", "contes of this", "the address on this"}
footer_geo_frac  = 0.88  # y-fraction threshold (>88% = footer zone)

for page_no, page in enumerate(doc.pages, start=1):
    page_height  = page.size.height if page.size else 2200
    page_elements = []
    layout_data["page_stats"][f"page_{page_no}"] = {
        "page_height": page_height,
        "element_count": 0,
        "header_count": 0,
        "footer_count": 0,
        "table_count": 0,
    }

for item, level in doc.iterate_items():
    item_dict = {
        "type": type(item).__name__,
        "label": getattr(item, "label", None),
        "text": None,
        "page": None,
        "bbox": None,
        "y_frac": None,
        "is_header_text": False,
        "is_footer_text": False,
        "is_footer_geo": False,
    }

    # Extract text
    if hasattr(item, "text"):
        item_dict["text"] = item.text
    elif hasattr(item, "export_to_markdown"):
        item_dict["text"] = item.export_to_markdown()

    # Extract bounding box / page info
    if hasattr(item, "prov") and item.prov:
        prov = item.prov[0]
        item_dict["page"] = prov.page_no
        if hasattr(prov, "bbox") and prov.bbox:
            b = prov.bbox
            item_dict["bbox"] = {
                "l": b.l, "t": b.t, "r": b.r, "b": b.b
            }
            # Docling uses top=0 at top. We check y_bottom fraction.
            # page height needed — pull from page_stats if available
            pg_key = f"page_{prov.page_no}"
            ph = layout_data["page_stats"].get(pg_key, {}).get("page_height", 2200)
            # In Docling bbox, b > t (b is bottom, t is top from doc top)
            # Fraction = bottom / page_height
            item_dict["y_frac"] = round(b.b / ph, 4) if ph else None

    text_lower = (item_dict["text"] or "").lower()

    # Classify header / footer by keyword
    item_dict["is_header_text"] = any(kw in text_lower for kw in header_keywords)
    item_dict["is_footer_text"] = any(kw in text_lower for kw in footer_keywords)

    # Classify footer by geometry
    if item_dict["y_frac"] is not None:
        item_dict["is_footer_geo"] = item_dict["y_frac"] > footer_geo_frac

    raw_elements.append(item_dict)

    # ── Route to layout buckets ────────────────────────────────────────────
    label = str(item_dict.get("label", "")).lower()
    text  = item_dict["text"] or ""

    if "table" in label:
        tables_data.append({
            "page": item_dict["page"],
            "bbox": item_dict["bbox"],
            "markdown": text,
        })
        layout_data["tables"].append(item_dict)
        if item_dict["page"]:
            pg_key = f"page_{item_dict['page']}"
            layout_data["page_stats"].setdefault(pg_key, {}).setdefault("table_count", 0)
            layout_data["page_stats"][pg_key]["table_count"] = layout_data["page_stats"][pg_key].get("table_count", 0) + 1

    elif "header" in label or item_dict["is_header_text"]:
        layout_data["headers"].append(item_dict)
        if item_dict["page"]:
            pg_key = f"page_{item_dict['page']}"
            layout_data["page_stats"].setdefault(pg_key, {})["header_count"] = layout_data["page_stats"][pg_key].get("header_count", 0) + 1

    elif "footer" in label or item_dict["is_footer_text"] or item_dict["is_footer_geo"]:
        layout_data["footers"].append(item_dict)
        if item_dict["page"]:
            pg_key = f"page_{item_dict['page']}"
            layout_data["page_stats"].setdefault(pg_key, {})["footer_count"] = layout_data["page_stats"][pg_key].get("footer_count", 0) + 1

    else:
        layout_data["text_blocks"].append(item_dict)

    # ── Update element counts ──────────────────────────────────────────────
    if item_dict["page"]:
        pg_key = f"page_{item_dict['page']}"
        layout_data["page_stats"].setdefault(pg_key, {})
        layout_data["page_stats"][pg_key]["element_count"] = layout_data["page_stats"][pg_key].get("element_count", 0) + 1

print(f"   Total elements: {len(raw_elements)}")
print(f"   Tables found: {len(tables_data)}")
print(f"   Header elements: {len(layout_data['headers'])}")
print(f"   Footer elements: {len(layout_data['footers'])}")
print(f"   Text blocks: {len(layout_data['text_blocks'])}")

# ── Step 3: Extract transaction-like rows from tables ──────────────────────────
print("STEP 3: Analysing table structures for transaction rows...")

txn_candidates = []
date_pattern_hints = ["/25", "/2025", "/24"]
amount_hints = ["dr", "cr", "debit", "credit"]

for tbl in tables_data:
    md = tbl.get("markdown", "")
    lines = [l.strip() for l in md.split("\n") if l.strip()]
    for line in lines:
        line_lower = line.lower()
        has_date = any(h in line for h in date_pattern_hints)
        has_amount = any(h in line_lower for h in amount_hints)
        if has_date:
            txn_candidates.append({
                "page": tbl["page"],
                "raw_line": line,
                "has_date": has_date,
                "has_amount": has_amount,
            })

print(f"   Transaction-like rows in tables: {len(txn_candidates)}")

# ── Step 4: Export Markdown ────────────────────────────────────────────────────
print("STEP 4: Exporting full document markdown...")
try:
    full_md = doc.export_to_markdown()
    md_path = os.path.join(OUT_DIR, "docling_full.md")
    with open(md_path, "w", encoding="utf-8") as f:
        f.write(full_md)
    print(f"   Markdown saved: {md_path}")
except Exception as e:
    print(f"   WARNING: Markdown export failed: {e}")
    full_md = ""

# ── Step 5: Save JSON outputs ──────────────────────────────────────────────────
print("STEP 5: Saving JSON outputs...")

save_json("raw_output.json", {
    "engine": "docling",
    "pdf": os.path.basename(PDF_PATH),
    "elapsed_seconds": round(elapsed, 2),
    "total_elements": len(raw_elements),
    "elements": raw_elements,
})

save_json("tables.json", {
    "engine": "docling",
    "table_count": len(tables_data),
    "txn_candidate_count": len(txn_candidates),
    "tables": tables_data,
    "txn_candidates": txn_candidates,
})

save_json("layout.json", {
    "engine": "docling",
    "summary": {
        "total_elements": len(raw_elements),
        "header_elements": len(layout_data["headers"]),
        "footer_elements": len(layout_data["footers"]),
        "table_elements": len(layout_data["tables"]),
        "text_blocks": len(layout_data["text_blocks"]),
    },
    "page_stats": layout_data["page_stats"],
    "headers": layout_data["headers"],
    "footers": layout_data["footers"],
})

# ── Step 6: Generate Summary ───────────────────────────────────────────────────
print("STEP 6: Generating summary.md...")

# Count footer leaks - elements labelled as footer that contain known HDFC footer text
hdfc_footer_strings = [
    "HDFC BANK LIMITED",
    "Registered Offce Address",
    "Closing balance includes",
    "GSTN27AAACH2702HZ0",
    "Contes of this statemen",
    "The address on this",
    "Senapan Bapar Marg",
    "Mumbai 400013",
]

footer_leak_count = 0
footer_leak_details = []

for el in raw_elements:
    text = el.get("text") or ""
    is_classified_footer = el in layout_data["footers"]
    for fs in hdfc_footer_strings:
        if fs.lower() in text.lower():
            if not is_classified_footer:
                # This is a leak — footer content NOT classified as footer
                footer_leak_count += 1
                footer_leak_details.append({
                    "text_snippet": text[:120],
                    "page": el["page"],
                    "label": str(el.get("label")),
                    "y_frac": el.get("y_frac"),
                    "classified_as_footer": is_classified_footer,
                    "matched_string": fs,
                })
            break

# CURRENT ENGINE baseline (from existing investigation)
CURRENT_TXNS      = 107
CURRENT_REJECTS   = 14
CURRENT_ANOMALIES = 27
CURRENT_HDR_LEAKS = 10  # known from existing findings.md

summary_lines = [
    "# P6B — Docling Investigation: HDFC PDF",
    "",
    "## Engine",
    "**Docling** (layout-understanding pre-processor)",
    f"- Version: {docling.__version__}",
    f"- Processing time: {elapsed:.1f}s",
    "",
    "## PDF Analysed",
    f"`{os.path.basename(PDF_PATH)}`",
    "",
    "## Extraction Metrics",
    "",
    "### Layout Elements Detected",
    f"| Metric | Docling | Current Engine (Baseline) |",
    f"|--------|---------|--------------------------|",
    f"| Header elements | {len(layout_data['headers'])} | N/A |",
    f"| Footer elements classified | {len(layout_data['footers'])} | N/A |",
    f"| Table elements | {len(layout_data['tables'])} | N/A |",
    f"| Text blocks | {len(layout_data['text_blocks'])} | N/A |",
    f"| Total elements | {len(raw_elements)} | N/A |",
    "",
    "### Footer Leakage Analysis",
    f"| Metric | Docling | Current Engine (Baseline) |",
    f"|--------|---------|--------------------------|",
    f"| Footer elements correctly classified | {len(layout_data['footers'])} | 0 (no classification) |",
    f"| HDFC footer strings leaking into non-footer elements | **{footer_leak_count}** | **10** |",
    "",
]

if footer_leak_details:
    summary_lines += [
        "### Footer Leak Details (Docling)",
        "These are HDFC footer strings found inside non-footer classified elements:",
        "",
    ]
    for i, detail in enumerate(footer_leak_details[:10], 1):
        summary_lines.append(f"**Leak {i}** — Page {detail['page']} | Label: `{detail['label']}` | y_frac: {detail['y_frac']}")
        summary_lines.append(f"```")
        summary_lines.append(detail["text_snippet"])
        summary_lines.append(f"```")
        summary_lines.append("")
else:
    summary_lines += [
        "### Footer Classification Result",
        "**No footer leaks detected** — Docling successfully classified all HDFC footer",
        "content as footer elements, preventing them from entering the transaction stream.",
        "",
    ]

summary_lines += [
    "### Table Detection",
    f"- Tables detected by Docling: **{len(tables_data)}**",
    f"- Transaction-candidate rows in tables: **{len(txn_candidates)}**",
    "",
]

if tables_data:
    summary_lines.append("#### Table Previews")
    for i, tbl in enumerate(tables_data[:3], 1):
        summary_lines.append(f"**Table {i}** — Page {tbl['page']}")
        md_preview = (tbl.get("markdown") or "")[:500]
        summary_lines.append(f"```markdown")
        summary_lines.append(md_preview)
        summary_lines.append(f"```")
        summary_lines.append("")

summary_lines += [
    "## Key Questions — HDFC",
    "",
    "### Q1: Does Docling recover correct balances?",
    "→ Docling does NOT run ledger validation — it is a layout engine, not an accounting",
    "engine. Balance extraction requires our Coordinate Parser V2 + Ledger Truth on top.",
    "However, if Docling eliminates footer contamination, balance anomalies caused by",
    "footer text merging into narration will be resolved upstream.",
    "",
    "### Q2: Are headers/footers completely absent from transaction content?",
    f"→ Footer leaks into non-footer elements: **{footer_leak_count}**",
    f"  (Baseline: 10 header/footer leaks in current engine)",
    "",
    "### Q3: Can Docling detect table structure?",
    f"→ Tables detected: **{len(tables_data)}**",
    f"  Transaction rows extracted from tables: **{len(txn_candidates)}**",
    "",
    "## Page-Level Statistics",
    "",
]

for pg, stats in sorted(layout_data["page_stats"].items()):
    summary_lines.append(f"**{pg}**: {stats.get('element_count', 0)} elements | "
                         f"{stats.get('header_count', 0)} headers | "
                         f"{stats.get('footer_count', 0)} footers | "
                         f"{stats.get('table_count', 0)} tables")

summary_lines += [
    "",
    "## Comparison to Current Engine",
    "",
    f"| Metric | Current Engine | Docling |",
    f"|--------|---------------|---------|",
    f"| Total Transactions | {CURRENT_TXNS} | {len(txn_candidates)} (table rows) |",
    f"| Rejects | {CURRENT_REJECTS} | N/A |",
    f"| Anomalies | {CURRENT_ANOMALIES} | N/A (no accounting layer) |",
    f"| Footer Leaks | {CURRENT_HDR_LEAKS} | {footer_leak_count} |",
    f"| Processing Time | ~120s (OCR) | {elapsed:.1f}s |",
    "",
    "## Raw Data Files",
    f"- `raw_output.json` — all {len(raw_elements)} Docling elements",
    f"- `tables.json` — {len(tables_data)} tables + {len(txn_candidates)} txn candidates",
    f"- `layout.json` — header/footer/table classification",
    f"- `docling_full.md` — full document markdown export",
    "",
    "## Preliminary Verdict",
]

if footer_leak_count < CURRENT_HDR_LEAKS:
    summary_lines += [
        f"✅ **Docling REDUCES footer leakage**: {footer_leak_count} vs {CURRENT_HDR_LEAKS} (current engine).",
        "This indicates Docling's layout classification correctly identifies HDFC footer blocks.",
        "As a pre-processor, Docling could eliminate the footer contamination at source.",
    ]
elif footer_leak_count == 0:
    summary_lines += [
        "✅ **Docling ELIMINATES footer leakage**: 0 leaks vs 10 in current engine.",
        "Strong evidence for adopting Docling as a pre-processing layer for HDFC PDFs.",
    ]
else:
    summary_lines += [
        f"⚠️ **Docling does NOT fully eliminate footer leakage**: {footer_leak_count} leaks remain.",
        "Further analysis required.",
    ]

summary_path = os.path.join(OUT_DIR, "summary.md")
with open(summary_path, "w", encoding="utf-8") as f:
    f.write("\n".join(summary_lines))
print(f"   Saved: {summary_path}")

# ── Done ────────────────────────────────────────────────────────────────────────
print()
print("=" * 70)
print("DOCLING HDFC INVESTIGATION COMPLETE")
print("=" * 70)
print(f"Total elements:     {len(raw_elements)}")
print(f"Tables detected:    {len(tables_data)}")
print(f"Footer elements:    {len(layout_data['footers'])}")
print(f"Footer leaks:       {footer_leak_count}")
print(f"Baseline (current): {CURRENT_HDR_LEAKS} footer leaks")
print(f"Processing time:    {elapsed:.1f}s")
print()
print(f"Output directory:   {OUT_DIR}")
