"""
P6B — Current Engine Layout Capture: HDFC PDF
===============================================
READ-ONLY. Does NOT modify any production parser.

This script captures layout intelligence from the CURRENT ENGINE
using pdfplumber (already installed) to extract geometric structure
as a cross-engine comparison baseline.

Outputs (saved to investigations/HDFC/):
  - current_layout.json   : page-level layout from pdfplumber
  - current_tables.json   : table extraction via pdfplumber
  - current_summary.md    : baseline layout findings

Run with:
    python run_current_engine_layout.py
"""

import json
import os
import time
import re
from pathlib import Path

PDF_PATH = r"Z:\CA\validation_lab\backend\temp\JOB_20260614_233121_48AC_Acct Statement_3644_14032026_13.08.12 1 (1)_page-0006.pdf"
OUT_DIR  = r"Z:\CA\investigations\HDFC"

os.makedirs(OUT_DIR, exist_ok=True)

def save_json(filename, data):
    path = os.path.join(OUT_DIR, filename)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False, default=str)
    print(f"   Saved: {path}")
    return path

# ── Known HDFC footer / header signatures ─────────────────────────────────────
HEADER_KEYWORDS = [
    "From:", "To:", "Statement of account", "Generated On", "Generated By",
    "Requesting Branch", "Date", "Narration", "Chq./Ref.No.",
    "Value Dt", "Withdrawal", "Deposit", "Closing Balance",
]
FOOTER_KEYWORDS = [
    "HDFC BANK LIMITED", "Registered Offce Address", "Closing balance includes",
    "GSTN", "Mumbai 400013", "Senapati Bapat", "Lowe Parel",
    "Contents of this statement", "Contes of this statemen",
    "The address on this", "tbranch", "t branch",
    "State accoun", "State account",
]

FOOTER_GEO_FRAC = 0.88  # bottom 12% of page = footer zone

print("=" * 70)
print("P6B — Current Engine Layout Capture: HDFC PDF")
print("=" * 70)

try:
    import pdfplumber
    print("[OK] pdfplumber available")
except ImportError:
    print("ERROR: pdfplumber not installed. Run: pip install pdfplumber")
    exit(1)

try:
    import fitz  # PyMuPDF
    print("[OK] PyMuPDF (fitz) available")
    HAS_FITZ = True
except ImportError:
    print("[WARN] PyMuPDF not available -- skipping text block geometry")
    HAS_FITZ = False

t0 = time.time()

# ── pdfplumber extraction ──────────────────────────────────────────────────────
print("\nSTEP 1: Extracting layout with pdfplumber...")

page_stats = {}
all_words   = []
table_data  = []
header_rows = []
footer_rows = []
body_rows   = []

with pdfplumber.open(PDF_PATH) as pdf:
    num_pages = len(pdf.pages)
    print(f"   PDF pages: {num_pages}")

    for pg_idx, page in enumerate(pdf.pages, start=1):
        pg_key = f"page_{pg_idx}"
        ph = page.height
        pw = page.width

        # Extract words
        words = page.extract_words() or []
        page_words = []
        page_headers = []
        page_footers = []
        page_body    = []

        for w in words:
            # Compute y fraction (pdfplumber y is from TOP)
            y0 = w.get("top", 0)
            y1 = w.get("bottom", 0)
            yc = (y0 + y1) / 2
            y_frac = yc / ph if ph else 0

            word_entry = {
                "text": w["text"],
                "x0": round(w["x0"], 1),
                "y0": round(y0, 1),
                "x1": round(w["x1"], 1),
                "y1": round(y1, 1),
                "y_frac": round(y_frac, 4),
                "page": pg_idx,
                "page_height": ph,
                "page_width": pw,
                "is_header": False,
                "is_footer": False,
            }
            page_words.append(word_entry)
            all_words.append(word_entry)

        # Build text lines from words grouped by y-band
        # Group words within 5px of same y into lines
        line_groups: dict[float, list] = {}
        for w in page_words:
            bucket = round(w["y0"] / 5) * 5
            line_groups.setdefault(bucket, []).append(w)

        page_text_lines = []
        for bucket in sorted(line_groups.keys()):
            group = sorted(line_groups[bucket], key=lambda x: x["x0"])
            line_text = " ".join(g["text"] for g in group)
            yc = group[0]["y0"] if group else 0
            y_frac = yc / ph if ph else 0

            is_hdr = any(kw.lower() in line_text.lower() for kw in HEADER_KEYWORDS)
            is_ftr = (
                y_frac > FOOTER_GEO_FRAC
                or any(kw.lower() in line_text.lower() for kw in FOOTER_KEYWORDS)
            )

            line_entry = {
                "text": line_text,
                "y_bucket": bucket,
                "y_frac": round(y_frac, 4),
                "page": pg_idx,
                "word_count": len(group),
                "is_header": is_hdr,
                "is_footer": is_ftr,
            }
            page_text_lines.append(line_entry)

            if is_hdr:
                page_headers.append(line_entry)
            elif is_ftr:
                page_footers.append(line_entry)
            else:
                page_body.append(line_entry)

        header_rows.extend(page_headers)
        footer_rows.extend(page_footers)
        body_rows.extend(page_body)

        # Extract tables via pdfplumber
        pg_tables = page.extract_tables() or []
        for t_idx, tbl in enumerate(pg_tables):
            table_data.append({
                "page": pg_idx,
                "table_index": t_idx,
                "row_count": len(tbl),
                "col_count": max((len(r) for r in tbl), default=0),
                "rows": tbl,
            })

        page_stats[pg_key] = {
            "page_height": ph,
            "page_width": pw,
            "word_count": len(words),
            "text_line_count": len(page_text_lines),
            "header_line_count": len(page_headers),
            "footer_line_count": len(page_footers),
            "body_line_count": len(page_body),
            "table_count": len(pg_tables),
        }

elapsed = time.time() - t0
print(f"   pdfplumber done in {elapsed:.1f}s")
print(f"   Total words: {len(all_words)}")
print(f"   Header lines: {len(header_rows)}")
print(f"   Footer lines: {len(footer_rows)}")
print(f"   Body lines: {len(body_rows)}")
print(f"   Tables: {len(table_data)}")

# ── PyMuPDF text block extraction (optional richer geometry) ──────────────────
fitz_blocks = []
if HAS_FITZ:
    print("\nSTEP 2: Extracting text blocks with PyMuPDF...")
    doc = fitz.open(PDF_PATH)
    for pg_idx in range(len(doc)):
        page = doc[pg_idx]
        ph = page.rect.height
        blocks = page.get_text("blocks")  # (x0, y0, x1, y1, text, block_no, block_type)
        for blk in blocks:
            x0, y0, x1, y1, text, block_no, block_type = blk
            y_frac = y1 / ph if ph else 0
            is_ftr = (
                y_frac > FOOTER_GEO_FRAC
                or any(kw.lower() in text.lower() for kw in FOOTER_KEYWORDS)
            )
            is_hdr = any(kw.lower() in text.lower() for kw in HEADER_KEYWORDS)
            fitz_blocks.append({
                "page": pg_idx + 1,
                "block_no": block_no,
                "block_type": block_type,  # 0=text, 1=image
                "x0": round(x0, 1), "y0": round(y0, 1),
                "x1": round(x1, 1), "y1": round(y1, 1),
                "y_frac": round(y_frac, 4),
                "text": text.strip()[:200],
                "is_footer": is_ftr,
                "is_header": is_hdr,
            })
    doc.close()
    print(f"   PyMuPDF blocks: {len(fitz_blocks)}")
    fitz_footer_blocks = [b for b in fitz_blocks if b["is_footer"]]
    fitz_header_blocks = [b for b in fitz_blocks if b["is_header"]]
    print(f"   Footer blocks: {len(fitz_footer_blocks)}")
    print(f"   Header blocks: {len(fitz_header_blocks)}")

# ── Analyse footer leak potential ─────────────────────────────────────────────
print("\nSTEP 3: Analysing footer leak potential...")

# "Footer leak" = a line with HDFC footer text NOT in the footer zone (y_frac < 0.88)
# These would be footer lines that appear mid-page and get swept into narrations
footer_leaks = []
for line in header_rows + body_rows:
    text_lower = line["text"].lower()
    for kw in FOOTER_KEYWORDS:
        if kw.lower() in text_lower and line["y_frac"] < FOOTER_GEO_FRAC:
            footer_leaks.append({
                **line,
                "leaked_keyword": kw,
            })
            break

print(f"   Footer text in non-footer zone (leaks): {len(footer_leaks)}")

# ── Save outputs ───────────────────────────────────────────────────────────────
print("\nSTEP 4: Saving JSON outputs...")

save_json("current_layout.json", {
    "engine": "current_engine_pdfplumber",
    "elapsed_seconds": round(elapsed, 2),
    "total_words": len(all_words),
    "page_count": num_pages,
    "page_stats": page_stats,
    "header_lines": header_rows,
    "footer_lines": footer_rows,
    "body_lines": body_rows[:500],  # truncate body for filesize
    "fitz_blocks": fitz_blocks if HAS_FITZ else [],
})

save_json("current_tables.json", {
    "engine": "current_engine_pdfplumber",
    "table_count": len(table_data),
    "tables": table_data,
})

# ── Generate summary ───────────────────────────────────────────────────────────
print("\nSTEP 5: Generating current_layout_summary.md...")

# Known baseline from existing run_investigation.py output
CURRENT_TXNS      = 107
CURRENT_REJECTS   = 14
CURRENT_ANOMALIES = 27
CURRENT_HDR_LEAKS = 10

lines_out = [
    "# P6B — Current Engine Layout Baseline: HDFC PDF",
    "",
    "## Engine",
    "**Current Engine** — pdfplumber geometry analysis (READ-ONLY, no parser modification)",
    f"- pdfplumber extraction time: {elapsed:.1f}s",
    "",
    "## PDF Analysed",
    f"`{os.path.basename(PDF_PATH)}`",
    "",
    "## From Existing Investigation (run_investigation.py output)",
    "",
    f"| Metric | Value |",
    f"|--------|-------|",
    f"| Transactions extracted | {CURRENT_TXNS} |",
    f"| Rejects | {CURRENT_REJECTS} |",
    f"| Anomalies (suspicious_fields) | {CURRENT_ANOMALIES} |",
    f"| Footer leaks (known) | {CURRENT_HDR_LEAKS} |",
    "",
    "## Layout Geometry (pdfplumber)",
    "",
    f"| Metric | Value |",
    f"|--------|-------|",
    f"| Total words extracted | {len(all_words)} |",
    f"| Header-classified lines | {len(header_rows)} |",
    f"| Footer-classified lines | {len(footer_rows)} |",
    f"| Body lines | {len(body_rows)} |",
    f"| Tables detected | {len(table_data)} |",
    f"| Footer leaks (geo analysis) | **{len(footer_leaks)}** |",
    "",
    "## Page Statistics",
    "",
]

for pg_key, stats in sorted(page_stats.items()):
    lines_out.append(
        f"**{pg_key}**: {stats['word_count']} words | "
        f"{stats['header_line_count']} header lines | "
        f"{stats['footer_line_count']} footer lines | "
        f"{stats['body_line_count']} body lines | "
        f"{stats['table_count']} tables"
    )

lines_out += [
    "",
    "## Footer Leak Analysis",
    f"Footer-text found OUTSIDE footer zone (y_frac < {FOOTER_GEO_FRAC}): **{len(footer_leaks)}**",
    "",
]

if footer_leaks:
    lines_out.append("### Leaked Footer Fragments")
    for i, lk in enumerate(footer_leaks[:10], 1):
        lines_out.append(
            f"**Leak {i}** — Page {lk['page']} | y_frac={lk['y_frac']} | "
            f"keyword: `{lk['leaked_keyword']}`"
        )
        lines_out.append(f"```")
        lines_out.append(lk["text"][:200])
        lines_out.append(f"```")
        lines_out.append("")

lines_out += [
    "## Tables (pdfplumber)",
    f"Tables detected: **{len(table_data)}**",
    "",
]

for i, tbl in enumerate(table_data[:3], 1):
    lines_out.append(f"**Table {i}** — Page {tbl['page']} | {tbl['row_count']} rows × {tbl['col_count']} cols")
    if tbl["rows"]:
        header_row = tbl["rows"][0] if tbl["rows"] else []
        lines_out.append(f"  Header row: `{' | '.join(str(c) for c in header_row[:6])}`")
    lines_out.append("")

lines_out += [
    "## Root Cause Summary (from prior investigation)",
    "",
    "### ISSUE-HDFC-001: Footer Merging into Narration",
    "- V2 bypasses header_suppression.py entirely",
    "- Row detector blindly appends non-anchor rows to current transaction block",
    "",
    "### ISSUE-HDFC-002: Suppression Algorithm Failure",
    "- Exact string match fails due to OCR noise in footer text",
    "- Footer paragraphs are long and OCR-unstable",
    "",
    "### ISSUE-HDFC-003: Row Grouping Vulnerability",
    "- detect_transaction_blocks has no admission test for continuation rows",
    "- Any row without a date in date-zone is blindly appended",
    "",
    "## This is the Baseline for Docling/MinerU Comparison",
    "",
    f"| Metric | Current Engine |",
    f"|--------|---------------|",
    f"| Footer leaks (investigation) | {CURRENT_HDR_LEAKS} |",
    f"| Footer leaks (geometry) | {len(footer_leaks)} |",
    f"| Tables detected (pdfplumber) | {len(table_data)} |",
    f"| Transaction count | {CURRENT_TXNS} |",
]

summary_path = os.path.join(OUT_DIR, "current_layout_summary.md")
with open(summary_path, "w", encoding="utf-8") as f:
    f.write("\n".join(lines_out))
print(f"   Saved: {summary_path}")

print()
print("=" * 70)
print("CURRENT ENGINE LAYOUT CAPTURE COMPLETE")
print("=" * 70)
print(f"Words extracted:  {len(all_words)}")
print(f"Header lines:     {len(header_rows)}")
print(f"Footer lines:     {len(footer_rows)}")
print(f"Footer leaks:     {len(footer_leaks)}")
print(f"Tables:           {len(table_data)}")
